### ISSUE TITLE
Некорректная работа вкладок в админке

### ISSUE THREAD

**Issue by 64j** [mnoskov/evocms-directory#6]
Некорректно работают вкладки в админке без GET параметров &a=, &id=, &type= 
В плагине нужно поправить 
https://github.com/mnoskov/evocms-directory/blob/master/plugins/Directory.php#L13

```php
'tree_page_click' => route('directory::show', $params['ph']['id']),
```
заменить на
```php
'tree_page_click' => route('directory::show', $params['ph']['id']) . '?id=' . $params['ph']['id'],
```

**Comment by 0test** [comment]
+1
